id: I029DE94A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:03:47+00:00'
last_modified: '2022-06-08T09:48:44.020732+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22110
  title: གསུང་འབུམ། རྒྱལ་ཚབ་རྗེ། ༼བཀྲས་ལྷུན་པར་རྙིང་བསྐྱར་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EB07:
      image_group_id: I00KG03914
      title: Volume 1 of gsung 'bum/_rgyal tshab rje (gelek)
      total_pages: 512
      order: 1
      base_file: EB07.txt
    389C:
      image_group_id: I00KG03915
      title: Volume 2 of gsung 'bum/_rgyal tshab rje (gelek)
      total_pages: 605
      order: 2
      base_file: 389C.txt
    3E6D:
      image_group_id: I00KG03916
      title: Volume 3 of gsung 'bum/_rgyal tshab rje (gelek)
      total_pages: 0
      order: 3
      base_file: 3E6D.txt
    F1BD:
      image_group_id: I00KG03917
      title: Volume 4 of gsung 'bum/_rgyal tshab rje (gelek)
      total_pages: 532
      order: 4
      base_file: F1BD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
