id: I029DE94A
legacy_id: P006984
ocr_import_info:
  bdrc_scan_id: W22110
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T11:59:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:34:44.789281+00:00'
last_modified: 2022-09-02 04:35:43.082245
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22110
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22110
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། རྒྱལ་ཚབ་རྗེ། ༼བཀྲས་ལྷུན་པར་རྙིང་བསྐྱར་པར་མ།༽
  author: རྒྱལ་ཚབ་དར་མ་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.7672930375204242
  ocr_word_median_confidence_index: 0.8500000238418579
quality: null
bases:
  I00KG03917:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03917
      total_pages: 532
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I00KG03917.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7800963933196291
    legacy_id: v004
  I00KG03914:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03914
      total_pages: 512
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03914.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7310321335184509
    legacy_id: v001
  I00KG03915:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03915
      total_pages: 605
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00KG03915.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.7858095579877743
    legacy_id: v002
  I00KG03918:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03918
      total_pages: 584
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I00KG03918.txt
    statistics:
      ocr_word_median_confidence_index: 0.8399999737739563
      ocr_word_mean_confidence_index: 0.7651935338423452
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
