id: P006984
initial_creation_type: ocr
source_metadata:
  id: bdr:W22110
  title: གསུང་འབུམ། རྒྱལ་ཚབ་རྗེ། ༼བཀྲས་ལྷུན་པར་རྙིང་བསྐྱར་པར་མ།༽
  author: ''
  volumes:
    74a8de33f399443d824b3a45c7f94f26:
      image_group_id: I00KG03914
      title: ''
      volume_number: 1
      total_pages: 512
    3aa06445638e4d9383fc7e8a07c7a961:
      image_group_id: I00KG03915
      title: ''
      volume_number: 2
      total_pages: 605
    7966659654184180897cd7fddb50f729:
      image_group_id: I00KG03916
      title: ''
      volume_number: 3
      total_pages: 0
    ce59646fbb8841318a235df090d27bd0:
      image_group_id: I00KG03917
      title: ''
      volume_number: 4
      total_pages: 532
    d780bc61b1c449f393f30af6863ec618:
      image_group_id: I00KG03918
      title: ''
      volume_number: 5
      total_pages: 584
    f9761090b7ac4c689663ff9935a2e781:
      image_group_id: I00KG03919
      title: ''
      volume_number: 6
      total_pages: 0
    4153a4ed5c9b49edadc388a1d57f409d:
      image_group_id: I00KG03920
      title: ''
      volume_number: 7
      total_pages: 0
    e7357d845a214431bd3d0ebe4d355756:
      image_group_id: I00KG03921
      title: ''
      volume_number: 8
      total_pages: 0
    5a8013401f3544828f885741ad14141c:
      image_group_id: I00KG03922
      title: ''
      volume_number: 9
      total_pages: 0
    d3b547f7e5c5430899f59355963ee546:
      image_group_id: I00KG03923
      title: ''
      volume_number: 10
      total_pages: 0
ebook_metadata:
  title: གསུང་འབུམ། རྒྱལ་ཚབ་རྗེ། ༼བཀྲས་ལྷུན་པར་རྙིང་བསྐྱར་པར་མ།༽
  author: ''
  sku: P006984
  cover: cover.jpg
  layers:
  - pagination
